language: cpp
compiler:
  - gcc
  - clang

sudo: required
  
before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 && brew link --force llvm35; fi
  - rvm use $RVM --install --binary --fuzzy
  - gem update --system
  - gem --version
  - cd gtest-1.7.0 && ./configure && make; cd ..

script:
  - make
  - make test
  
branches:
  only:
    - master
  
os:
  - linux
  - osx